### ISSUE TITLE
Hello! 👋 consider loco.rs

### ISSUE THREAD

**Issue by jondot** [clowzed/sero#18]
Hi!
This is a really cool project I'm using for myself. I'm also the author of Loco (https://loco.rs), the "Rails for Rust". You've got a lot of infrastructure (auth, db handling, etc.) that we've already built, and by chance we're also strongly relying on SeaORM

Give it a try, you can build a full app in 3-4 minutes: https://loco.rs/docs/getting-started/tour/

Maybe consider Loco for `sero` and save a lot of infra work

**Comment by clowzed** [comment]
@jondot Hi!  I think i'll give it a try in another repository! Thank you for reaching me!
