### ISSUE TITLE
Can't initialize due to postgres version error

### ISSUE THREAD

**Issue by emenel** [clowzed/sero#19]
Hi. I'm trying to get sero setup to test (this is exactly what i've been looking for! :) ), but running into this error when I attempt to launch the processes with docker compose:

`The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.1`

I dug through the config to see where the version of Postgres was specified but can't find anything so far. (I'm not a docker expert by any means).

Thanks for any assistance.

**Comment by clowzed** [comment]
Hi. 
That was my big fault to use` postgres:latest `in `docker-compose.yml.` 
There are some possible solutions for this situation.

1)  If you do not have any valuable information stored you can simply remove all volumes with 
`docker-compose down --volumes`. Then open docker-compose.yml and change postgres:latest to postgres:<version you want>. This will prevent any unexpected behavior.

2) Simply change  postgres:latest to postgres:15 and run `docker-compose up`. This will keep your information untouched and will resolve this issue.  In future release i will keep postgres version 15 to prevent this situations.

**Comment by clowzed** [comment]
Fixed. Update repository and run `docker-compose up`. Waiting for your reply

**Comment by emenel** [comment]
Thanks so much! I won’t be able to test until tomorrow and will let you know as soon as i can.

**Comment by clowzed** [comment]
@emenel 
I also tested it by myself and that resolved the issue!

**Comment by emenel** [comment]
Thanks! I'm seeing another error, which might make sense to post as a separate issue:

`invalid interpolation format for services.proxy.environment.[]: "DOLLAR=$". You may need to escape any $ with another $`

**Comment by clowzed** [comment]
OK! Will close this one as it has been solved.
