### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by schemetastic** [clowzed/sero#6]
Even though the “readme.md” file contains a statement that says “Distributed under the MIT License”, there is no text of the license or a link to that text, which could probably limit some people on the use of the project.

I'm not a lawyer to provide legal advice, but ideally a file with the text of the license should be included instead of a link, the file would contain the name of the author and also is easier to access (cause a website could have downtimes).

**Comment by clowzed** [comment]
@schemetastic Thank you for you issue! That's what I've forgot to do!

**Comment by schemetastic** [comment]
You're welcome, maybe I should keep an eye on this project 😉
